# Generated by Django 5.0.6 on 2024-06-12 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время выполнения"
            ),
        ),
    ]
